adv_cbv/urls.py
from os import name
from django.contrib import admin
from basic_app import views
from django.urls import re_path, path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    re_path(r'^$', views.IndexView.as_view(), name="index"),
    re_path(r'^basic_app/', include('basic_app.urls')),
]

basic_app/urls.py
from . import views
from django.urls import re_path, path

app_name = 'basic_app'

urlpatterns = [
    path('', views.SchoolListView.as_view(), name='school_list'),
    re_path('^(?P<pk>\d+)/', views.SchoolDetailView.as_view(), name='school_detail'),
    re_path('^create_school/$', views.SchoolCreateView.as_view(), name='create_school'),
    re_path('^update_school/(?P<pk>\d+)/$', views.SchoolUpdateView.as_view(), name='update_school'),
    re_path('^delete_school/(?P<pk>\d+)/$', views.SchoolDeleteView.as_view(), name='delete_school'),
]

basic_app/models.py
from django.db import models
from django.urls import reverse

# Create your models here.
class School(models.Model):
    '''Creates fields for the School Model and returns the school.name.'''
    name = models.CharField(max_length=256)
    principal = models.CharField(max_length=256)
    location = models.CharField(max_length=256)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        '''Returns the details of a specific school.'''
        return reverse("basic_app:school_detail", kwargs={'pk':self.pk})

class Student(models.Model):
    '''Creates fields for the Student Model and returns student.name.'''
    name = models.CharField(max_length=256)
    age = models.PositiveIntegerField()
    school = models.ForeignKey(School, related_name='students', on_delete=models.CASCADE) # Creates a many to one relationship between the School model and the school attribute in the Student Model.

    def __str__(self):
        return self.name

basic_app/views.py
from re import template
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.generic import (View, TemplateView, ListView, DetailView,
                                    CreateView, UpdateView, DeleteView)
from django.http import HttpResponse
from . import models

# Create your views here.

# def index(request):
#     return render(request, '../templates/basic_app/index.html')

# class CBView(TemplateView):
    # def get(self, request):
    #     return HttpResponse("Class Based Views ARE COOL")
# class IndexView(TemplateView):
#     template_name = 'index.html'

#     def get_context_data(self, **kwargs):
#         context = super().get_context_data(**kwargs)
#         context['inject_me'] = "A basic display of how to return a context in CBV using TemplateView."
#         return context

class IndexView(TemplateView):
    '''Connects a template to this Class-Base-View'''
    template_name = 'index.html'
    
    def get_context_data(self, **kwargs):
        '''Creates and return a context in a Class-Based-View'''
        context = super().get_context_data(**kwargs)
        context['school_list'] = ''
        return context


class SchoolListView(ListView):
    '''Renders the list of schools created in the School Model'''
    context_object_name = 'schools'
    model = models.School
    template_name = 'basic_app/school_list.html'

class SchoolDetailView(DetailView):
    '''Renders the details of each school created in the School Model'''
    context_object_name = 'school_detail'
    model = models.School
    template_name = 'basic_app/school_details.html'

class SchoolCreateView(CreateView):
    '''Create a new instance of school from the School Model in models.py'''
    fields = ('name', 'principal', 'location')
    model = models.School

class SchoolUpdateView(UpdateView):
    '''View for updating the fields of a school'''
    fields = ('name', 'principal')
    model = models.School

class SchoolDeleteView(DeleteView):
    '''View for deleting the fields of a school'''
    model = models.School
    success_url = reverse_lazy('basic_app:school_list')
    # template_name = 'basic_app/school_details.html'

basic_app/templates/basic_app/basic_app_base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- <title>Base</title> -->
    <title>{% block title %}{% endblock %}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <div class="container-fluid">
          <a class="navbar-brand" href="{% url 'index' %}">HOME</a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
              <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="{% url 'basic_app:school_list' %}">
                    Schools
                </a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'admin:index' %}">Admin</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'basic_app:create_school' %}">Create School</a>
              </li>
            </ul>
          </div>
        </div>
      </nav>

    <div class="container">
        {% block body_block %}

        {% endblock %}
    </div>
</body>
</html>

basic_app/templates/basic_app/school_confirm_delete.html
{% extends "basic_app/basic_app_base.html" %}

{% block title %}Delete School{% endblock %}

{% block body_block %}
<h1>Delete {{ school.name }}? </h1>
<form method="post" class="mt-5">
    {% csrf_token %}
    <input type="submit" value="Delete" class="btn btn-danger">
    <a class="float-end btn btn-primary" href="{% url 'basic_app:school_detail' pk=school.pk %}">Cancel</a>
</form>
{% endblock %}

basic_app/templates/basic_app/school_details.html
{% extends "basic_app/basic_app_base.html" %}
{% block title %}School Details{% endblock %}

{% block body_block %}
    <div class="p-5 mb-4 bg-light border rounded-3">
        <h1>Welcome to the School Details Page</h1>
        <h2>School Details: </h2>
        <p>Name: {{ school_detail.name }}</p>
        <p>Principal: {{ school_detail.principal }}</p>
        <p>Location: {{ school_detail.location }}</p>

        <h3>A List of all the students in this school</h3>
        {% for student in  school_detail.students.all %}
            <p>{{ student.name }}, who is {{ student.age }} years old</p>
        {% endfor %}

        <div class="container mt-5">
                <a class="btn btn-primary" href="{% url 'basic_app:update_school' pk=school_detail.pk %}">
                    Update
                </a>
                <a class="btn btn-danger" href="{% url 'basic_app:delete_school' pk=school_detail.pk %}">
                    Delete
                </a>
        </div>
    </div>
{% endblock %}

basic_app/templates/basic_app/school_form.html
{% extends "basic_app/basic_app_base.html" %}
{% block title %}Create New School{% endblock %}

{% block body_block %}
<h1>
    <!-- Checks if the instance of the pk exists. If it does not exist, it creates a new scholl. If it exists, it updates the existing school. -->
    {% if not form.instance.pk %}
    Create New School
    {% else %}
    Update Existing School
    {% endif %}
</h1>

<div class="form-group">
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" class="btn btn-primary" value="Submit">
    </form>
</div>
{% endblock %}

basic_app/templates/basic_app/school_list.html
{% extends "basic_app/basic_app_base.html" %}
{% block title %}List of Schools{% endblock %}

{% block body_block %}
    <h3>A List of schools owned by The Adiguns</h3>
    <ol>
    {% for school in schools %}
        <h5><li><a href="{{school.id}}">{{ school.name }}</a></li></h5>
    {% endfor %}
    </ol>
{% endblock%}

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- <title>Base</title> -->
    <title>{% block title %}{% endblock %}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <div class="container-fluid">
          <a class="navbar-brand" href="{% url 'index' %}">HOME</a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
              <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="{% url 'basic_app:school_list' %}">
                    Schools
                </a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'admin:index' %}">Admin</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'basic_app:create_school' %}">Create School</a>
              </li>
            </ul>
          </div>
        </div>
      </nav>

    <div class="container">
        {% block body_block %}

        {% endblock %}
    </div>
</body>
</html>

templates/index.html
<!DOCTYPE html>
{% extends "base.html" %}
{% block title %}Home{% endblock %}

{% block body_block %}
    <!-- <h1>Hello World! Index Home Page</h1> -->
    <!-- <h1>Testing TemplateView</h1>
    <h1>Injecting Context: {{ inject_me  }}</h1> -->
    <div class="p-5 mb-4 bg-light border rounded-3">
        Home Page!
    </div>
{% endblock %}